stages:
  - build

build-image:
  image: docker:latest
  stage: build
  only:
    - master
  script:
    - docker build -t $IMAGE $IMAGE_PATH
    - docker tag $IMAGEE $REGISTRY/$IMAGE
    - docker push $REGISTRY/$IMAGE