stages:
  - build

build-image:
  image: docker:latest
  stage: build
  only:
    - master
  script:
    - docker build -t $IMAGE:$CI_COMMIT_REF_NAME $IMAGE_PATH
    - docker tag $IMAGE:$CI_COMMIT_REF_NAME $REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME