stages:
  - build

build-image:
  image: docker:latest
  stage: build
  script:
    - docker build -t $IMAGE:7.3 $IMAGE_PATH
    - docker tag $IMAGE:7.3 $REGISTRY/$IMAGE:7.3
    - docker push $REGISTRY/$IMAGE:7.3