stages:
  - build

build-image:
  image: docker:latest
  stage: build
  script:
    - docker build -t $IMAGE:latest $IMAGE_PATH
    - docker tag $IMAGE:latest $REGISTRY/$IMAGE:latest
    - docker push $REGISTRY/$IMAGE:latest