stages:
  - magento2-php
  - magento2-nginx

build-magento2-php:
  image: docker:latest
  stage: magento2-php
  script:
    - docker build -t magento2-php:7.0 ./builds/php-fpm
    - docker tag magento2-php:7.0 $REGISTRY/magento2-php:7.0
    - docker push $REGISTRY/magento2-php:7.0

build-magento2-nginx:
  image: docker:latest
  stage: magento2-nginx
  script:
    - docker build -t magento2-nginx:latest ./builds/nginx
    - docker tag magento2-nginx:latest $REGISTRY/magento2-nginx:latest
    - docker push $REGISTRY/magento2-nginx:latest