stages:
  - build

build-image:
  image: docker:latest
  stage: build
  script:
    - docker build -t $IMAGE:7.1 $IMAGE_PATH
    - docker tag $IMAGE:7.1 $REGISTRY/$IMAGE:7.1
    - docker push $REGISTRY/$IMAGE:7.1