stages:
  - build

build-image:
  image: docker:latest
  stage: build
  only:
    - master
  script:
    - docker build -t $IMAGE:7.0 $IMAGE_PATH
    - docker tag $IMAGE:7.0 $REGISTRY/$IMAGE:7.0
    - docker push $REGISTRY/$IMAGE:7.0