stages:
  - build

build-image:
  image: docker:latest
  stage: build
  only:
    - master
  script:
    - echo $IMAGE
#    - docker build -t $IMAGE $PATH
#    - docker tag $IMAGE $REGISTRY/$IMAGE
#    - docker push $IMAGE/$IMAGE