stages:
  - build

build-image:
  image: docker:latest
  stage: build
  only:
    - master
  script:
    - docker build -t $IMAGE:latest $IMAGE_PATH
    - docker tag $IMAGEE:latest $REGISTRY/$IMAGE:latest
    - docker push $REGISTRY/$IMAGE:latest