version: '2'

services:
  magento2_nginx:
    image: nginx:latest
    links:
      - magento2_php
    volumes_from:
      - magento2_application
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./ssl:/etc/nginx/cert
    env_file:
      - ./env/nginx.env
    environment:
      - VIRTUAL_HOST=magento2.dev
      - MAGE_MODE=developer
      - MAGE_RUN_CODE=default
      - MAGE_RUN_TYPE=store
    command: /bin/bash -c "envsubst '$$VIRTUAL_HOST $$PHP_HOST $$PHP_PORT $$MAGE_MODE $$MAGE_ROOT $$MAGE_RUN_CODE $$MAGE_RUN_TYPE' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80:80
      - 443:443

  magento2_application:
    image: tianon/true
    volumes:
      - ./code:/var/www/html
      - ./shared:/var/www/html/var

  magento2_php:
    image: docker.pp.ua/magento2-php7.2
#    build: ./builds/php-fpm
    links:
      - magento2_mysql
    volumes_from:
      - magento2_application
    volumes:
      - ./config/composer/auth.json:/var/www/.composer/auth.json
      - ./config/composer/auth.json:/root/.composer/auth.json
      - ./config/ssh:/root/.ssh
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - ./env/php.env

  magento2_mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    volumes_from:
      - magento2_application
    ports:
      - 3307:3306
    expose:
      - 3306
    env_file:
      - ./env/mysql.env

  magento2_redis:
    image: redis
    #    command: redis-server --requirepass redispassword
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
#
#  magento2_rabbitmq:
#    image: rabbitmq
#    ports:
#      - 5672:5672
#    expose:
#      - 5672
#    volumes:
#      - ./data/rabbitmq:/var/lib/rabbitmq
#
#    magento2_elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
##    build: ./builds/elasticsearch
#    environment:
#      - discovery.type=single-node
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300