version: '3.7'

services:
  magento2_php_volumes:
    image: tianon/true
    volumes:
      - code:/var/www/html
      - ./config/composer/auth.json:/var/www/.composer/auth.json
      - ./config/composer/auth.json:/root/.composer/auth.json
#      - ./config/composer/auth.json:/var/www/html/var/composer_home/auth.json
      - ./config/ssh:/root/.ssh
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/magento2-php.ini

  magento2_nginx:
#    see link: https://web.docker.pp.ua/?page=1#!taglist/magento2-nginx
    image: docker.pp.ua/magento2-nginx:latest
#    build: ./builds-custom/nginx
    links:
      - magento2_php
    depends_on:
      - magento2_php
    volumes:
      - code:/var/www/html
#      - logs:/var/log/nginx:delegated
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./config/nginx/subdomain.conf:/etc/nginx/conf.d/subdomain.template
      - ./config/nginx/subdomains:/etc/nginx/conf.d/subdomains:rw
      - ./ssl:/etc/nginx/cert
    env_file:
      - ./env/nginx.env
    environment:
      - VIRTUAL_HOST=magento2.dev
      - MAGE_MODE=developer
      - MAGE_RUN_CODE=default
      - MAGE_RUN_TYPE=store
      - DOMAINS=magento2.local=default magento2.test=default
    command: /bin/bash -c "/usr/local/bin/docker-entrypoint.sh && exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80:80
      - 443:443

  magento2_php:
#    see link: https://web.docker.pp.ua/#!taglist/magento2-php
    image: docker.pp.ua/magento2-php:7.4
#    build: ./builds-custom/php
    links:
      - magento2_mysql
    depends_on:
      - magento2_mysql
      - magento2_mailhog
      - magento2_redis
      - magento2_elasticsearch
      - magento2_php_volumes
    volumes_from:
      - magento2_php_volumes
    volumes:
      - ./config/php/no_xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    env_file:
      - ./env/php.env

  magento2_php_xdebug:
#    see link: https://web.docker.pp.ua/#!taglist/magento2-php
    image: docker.pp.ua/magento2-php:7.4
#    build: ./builds-custom/php
    links:
      - magento2_mysql
    depends_on:
      - magento2_mysql
      - magento2_mailhog
      - magento2_redis
      - magento2_elasticsearch
      - magento2_php_volumes
    volumes_from:
      - magento2_php_volumes
    env_file:
      - ./env/php.env

  magento2_mysql:
    image: mysql:5.7
#    container_name: magento2_mysql
    volumes:
      - mysql:/var/lib/mysql:delegated
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3306
    expose:
      - 3306
    env_file:
      - ./env/mysql.env

  magento2_mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025
    ports:
      - 8025:8025

  magento2_redis:
    image: redis
    #    command: redis-server --requirepass magento2
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis:/data:delegated

  magento2_elasticsearch:
    image: docker.pp.ua/magento2-elasticsearch:latest
#    build: ./builds-custom/elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:delegated
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - logs:/usr/share/elasticsearch/logs:delegated
    expose:
      - 9200
    ports:
      - 9200:9200
      - 9300:9300

#  magento2_rabbitmq:
#    image: rabbitmq
#    ports:
#      - 4369:4369
#      - 5671:5671
#      - 5672:5672
#      - 25672:25672
#    expose:
#      - 4369
#      - 5671
#      - 5672
#      - 25672
#    volumes:
#      - rabbitmq:/var/lib/rabbitmq:delegated

volumes:
  code:
  mysql:
  redis:
  elasticsearch:
  rabbitmq:
#  logs:

x-mutagen:
  sync:
    defaults:
      mode: "two-way-safe"
      symlink:
        mode: "posix-raw"
      configurationBeta:
        permissions:
          defaultOwner: ${UID}
          defaultGroup: ${UID}
          defaultFileMode: "0666"
          defaultDirectoryMode: "0777"
      ignore:
        vcs: true
    code:
      alpha: "./code"
      beta: "volume://code"
      ignore:
        paths:
          - "var/*"
          - "generated/*"
          - "pub/static/*"
          - "pub/media/catalog/product/cache"
          - "pub/media/downloadable"