version: '2'

services:
  magento2_nginx:
    image: nginx:latest
    links:
      - magento2_php
    volumes_from:
      - magento2_application
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./ssl:/etc/nginx/cert
    env_file:
      - ./env/nginx.env
    environment:
      - VIRTUAL_HOST=magento2.dev
      - MAGE_MODE=developer
    command: /bin/bash -c "envsubst '$$VIRTUAL_HOST $$PHP_HOST $$PHP_PORT $$MAGE_MODE $$MAGE_ROOT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80:80
      - 443:443

  magento2_application:
    image: tianon/true
    volumes:
      - ./code:/var/www/html
      - ./shared:/var/www/html/var
      - ./shared/generated:/var/www/html/generated

  magento2_php:
    image: docker.pp.ua/magento2-php7.1
#    build: ./builds/7.1-fpm
    links:
      - magento2_mysql
    volumes_from:
      - magento2_application
    volumes:
      - ./config/composer/auth.json:/var/www/.composer/auth.json
      - ./config/composer/auth.json:/root/.composer/auth.json
      - ./config/ssh:/root/.ssh
    env_file:
      - ./env/php.env

  magento2_mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    volumes_from:
      - magento2_application
    ports:
      - 3307:3306
    expose:
      - 3306
    env_file:
      - ./env/mysql.env
      
#  magento2_redis:
#    image: redis
#    ports:
#      - 6379:6379
#    expose:
#      - 6379
#    volumes:
#      - ./data/redis:/data
#
#  magento2_elasticsearch:
#    build: ./builds/elasticsearch
#    environment:
#      - discovery.type=single-node
#    ports:
#      - 9200:9200
#      - 9300:9300