version: '3'

services:
  magento2_nginx:
#    see link: https://web.docker.pp.ua/?page=1#!taglist/magento2-nginx
    image: docker.pp.ua/magento2-nginx:latest
#    build: ./builds-custom/nginx
    links:
      - magento2_php
    depends_on:
      - magento2_php
    volumes:
      - ./code:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - /data/custom_templates/4/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/custom_templates/4/config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - /data/custom_templates/4/config/nginx/subdomain.conf:/etc/nginx/conf.d/subdomain.template
      - /data/custom_templates/4/config/nginx/subdomains:/etc/nginx/conf.d/subdomains:rw
      - /data/custom_templates/4/ssl:/etc/nginx/cert
    env_file:
      - /data/custom_templates/4/env/nginx.env
    environment:
      - VIRTUAL_HOST=magento2.dev
      - MAGE_MODE=developer
      - MAGE_RUN_CODE=default
      - MAGE_RUN_TYPE=store
      - DOMAINS=magento2.local=default magento2.test=default
    command: /bin/bash -c "/usr/local/bin/docker-entrypoint.sh && exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80
      - 443

  magento2_php:
#    see link: https://web.docker.pp.ua/#!taglist/magento2-php
    image: docker.pp.ua/magento2-php:latest
#    build: ./builds-custom/php
#    container_name: magento2_php
    links:
      - magento2_mysql
    depends_on:
      - magento2_mysql
      - magento2_mailhog
      - magento2_redis
      - magento2_elasticsearch
    volumes:
      - ./code:/var/www/html
      - /data/custom_templates/4/config/composer/auth.json:/var/www/.composer/auth.json
      - /data/custom_templates/4/config/composer/auth.json:/root/.composer/auth.json
      - /data/custom_templates/4/config/ssh:/root/.ssh
      - /data/custom_templates/4/config/php/php.ini:/usr/local/etc/php/conf.d/magento2-php.ini
    env_file:
      - /data/custom_templates/4/env/php.env
    ports:
      - 9000

  magento2_mysql:
    image: mysql:5.7
#    container_name: magento2_mysql
    volumes:
      - /data/custom_templates/4/data/mysql:/var/lib/mysql:rw
      - /data/custom_templates/4/config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - magento2_application
    ports:
      - 3306
    expose:
      - 3306
    env_file:
      - /data/custom_templates/4/env/mysql.env

  magento2_mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025
    ports:
      - 8025

  magento2_redis:
    image: redis
    #    command: redis-server --requirepass magento2
    ports:
      - 6379
    expose:
      - 6379
    volumes:
      - /data/custom_templates/4/data/redis:/data

  magento2_elasticsearch:
    image: docker.pp.ua/magento2-elasticsearch:latest
#    build: ./builds-custom/elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/custom_templates/4/data/elasticsearch:/usr/share/elasticsearch/data:rw
      - /data/custom_templates/4/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/custom_templates/4/logs/elasticsearch:/usr/share/elasticsearch/logs
    expose:
      - 9200
    ports:
      - 9200
      - 9300

#  magento2_rabbitmq:
#    image: rabbitmq
#    ports:
#      - 4369:4369
#      - 5671:5671
#      - 5672:5672
#      - 25672:25672
#    expose:
#      - 4369
#      - 5671
#      - 5672
#      - 25672
#    volumes:
#      - /data/custom_templates/4/data/rabbitmq:/var/lib/rabbitmq
