version: '2.2'

services:
  magento2_application:
    image: tianon/true
    volumes:
      - ${PWD}/code:/var/www/html
      - ${PWD}/shared:/var/www/html/var

  magento2_nginx:
#    build: ./builds/nginx
    image: nginx:latest
    links:
      - magento2_php
    depends_on:
      - magento2_php
      - magento2_application
    volumes_from:
      - magento2_application
    volumes:
      - ${PWD}/logs/nginx:/var/log/nginx
      - ${PWD}/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ${PWD}/ssl:/etc/nginx/cert
    env_file:
      - ./env/nginx.env
    environment:
      - VIRTUAL_HOST=magento2.dev
      - MAGE_MODE=developer
      - MAGE_RUN_CODE=default
      - MAGE_RUN_TYPE=store
    command: /bin/bash -c "envsubst '$$VIRTUAL_HOST $$PHP_HOST $$PHP_PORT $$MAGE_MODE $$MAGE_ROOT $$MAGE_RUN_CODE $$MAGE_RUN_TYPE' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80:80
      - 443:443

  magento2_php:
#    see link: https://web.docker.pp.ua/#!taglist/magento2-php
    image: docker.pp.ua/magento2-php:7.2
#    build: ./builds/php-fpm
    links:
      - magento2_mysql
    depends_on:
      - magento2_mysql
      - magento2_application
      - magento2_mailhog
      - magento2_redis
    volumes_from:
      - magento2_application
    volumes:
      - ${PWD}/config/composer/auth.json:/var/www/.composer/auth.json
      - ${PWD}/config/composer/auth.json:/root/.composer/auth.json
      - ${PWD}/config/composer/auth.json:/var/www/html/var/composer_home/auth.json
      - ${PWD}/config/ssh:/root/.ssh
      - ${PWD}/config/php/php.ini:/usr/local/etc/php/conf.d/magento2-php.ini
    env_file:
      - ./env/php.env

  magento2_mysql:
    image: mysql:5.7
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql
      - ${PWD}/config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - magento2_application
    volumes_from:
      - magento2_application
    ports:
      - 3307:3306
    expose:
      - 3306
    env_file:
      - ./env/mysql.env

  magento2_mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025
    ports:
      - 8025:8025

  magento2_redis:
    image: redis
    #    command: redis-server --requirepass magento2
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ${PWD}/data/redis:/data

#  magento2_rabbitmq:
#    image: rabbitmq
#    ports:
#      - 4369:4369
#      - 5671:5671
#      - 5672:5672
#      - 25672:25672
#    expose:
#      - 4369
#      - 5671
#      - 5672
#      - 25672
#    volumes:
#      - ${PWD}/data/rabbitmq:/var/lib/rabbitmq

#  magento2_elasticsearch:
#    build: ./builds/elasticsearch
#    environment:
#      - discovery.type=single-node
#    volumes:
#      - ${PWD}/data/elasticsearch:/usr/share/elasticsearch/data
#    expose:
#      - 9200
#    ports:
#      - 9200:9200
#      - 9300:9300